name: Update gitlab contributions
on:
  push:

jobs:
  update-gitlab-contributions-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update svg
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/playwright-container@v3.0.0
        uses: ianwalter/playwright-container@43940dfa7d309fe3569b9df407ae9e84dcbf2e7f
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /opt/playwright-browsers/chromium-857950/chrome-linux/chrome
        with:
          entrypoint: /bin/bash
        run: |
          ls -al /opt/playwright-browsers/
          yarn install
          node scripts/ci/update-gitlab-contributions.js

      # - name: Check for modified files
      #   id: git-check
      #   run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      # - name: Update changes in GitHub repository
      #   if: steps.git-check.outputs.modified == 'true'
      #   run: |
      #     git config --global user.name 'Jonathan Cardoso'
      #     git config --global user.email 'me@jonathancardoso.com'
      #     git add -A
      #     git commit -m 'add updated svg with gitlab contributions [skip ci]'
      #     git push
