name: Update gitlab contributions
on:
  push:

jobs:
  update-gitlab-contributions-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # GitHub already provides us with a Browser, so this is not needed :)
      # - name: Install Puppeteer Deps
      #   # Too lazy to create a docker image lol
      #   run: |
      #     sudo apt-get update \
      #     && sudo apt-get install -y wget gnupg ca-certificates procps libxss1 \
      #     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - \
      #     && sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
      #     && sudo apt-get update \
      #     && sudo apt-get install -y google-chrome-stable \
      #     && sudo rm -rf /var/lib/apt/lists/*

      - name: Retrieve latest SVG
        run: |
          yarn install
          node scripts/ci/update-gitlab-contributions.js
          ls -al
          git status

      # - name: Check for modified files
      #   id: git-check
      #   run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      # - name: Update changes in GitHub repository
      #   if: steps.git-check.outputs.modified == 'true'
      #   run: |
      #     git config --global user.name 'Jonathan Cardoso'
      #     git config --global user.email 'me@jonathancardoso.com'
      #     git add -A
      #     git commit -m 'add updated svg with gitlab contributions [skip ci]'
      #     git push
